### ISSUE TITLE
unxutils?

### ISSUE THREAD

**Issue by AlJohri** [uranusjr/make-it-please#1]
hi! just came across this on my github feed. I'm still currently on macOS but I'm interested in switching in the next year or so. I was wondering if http://unxutils.sourceforge.net/ might work more smoothly? any upsides to the bat script approach?

**Comment by uranusjr** [comment]
I’m not familiar with unxutils, but I’ve used GnuWin32 which looks similar., and it works well enough if you’re looking for those exact functionalities. https://en.wikipedia.org/wiki/GnuWin32

I don’t really care about those though. I was never good with shell stuff, and just use native tools (and some non builtin stuffs) after switching to Windows, so these are more for trivial cases that should have been totally Windows compatible but aren’t due to developer oversight.

Also I love my `#` hack so much I need to find an excuse to put it out 😏
